// Copyright (c) 2008 The Board of Trustees of The Leland Stanford Junior University
// Copyright (c) 2011, 2012 Open Networking Foundation
// Copyright (c) 2012, 2013 Big Switch Networks, Inc.
// This library was generated by the LoxiGen Compiler.
// See the file LICENSE.txt which should have been included in the source distribution

// Automatically generated by LOXI from template const.java
// Do not modify

package org.projectfloodlight.openflow.protocol;

import org.projectfloodlight.openflow.protocol.*;
import org.projectfloodlight.openflow.protocol.action.*;
import org.projectfloodlight.openflow.protocol.actionid.*;
import org.projectfloodlight.openflow.protocol.bsntlv.*;
import org.projectfloodlight.openflow.protocol.errormsg.*;
import org.projectfloodlight.openflow.protocol.meterband.*;
import org.projectfloodlight.openflow.protocol.instruction.*;
import org.projectfloodlight.openflow.protocol.instructionid.*;
import org.projectfloodlight.openflow.protocol.match.*;
import org.projectfloodlight.openflow.protocol.oxm.*;
import org.projectfloodlight.openflow.protocol.queueprop.*;
import org.projectfloodlight.openflow.types.*;
import org.projectfloodlight.openflow.util.*;
import org.projectfloodlight.openflow.exceptions.*;

public enum OFBsnPortCounter {
     BSN_PORT_COUNTER_RX_BYTES((byte) 0x0),
     BSN_PORT_COUNTER_RX_PACKETS_UNICAST((byte) 0x1),
     BSN_PORT_COUNTER_RX_PACKETS_BROADCAST((byte) 0x2),
     BSN_PORT_COUNTER_RX_PACKETS_MULTICAST((byte) 0x3),
     BSN_PORT_COUNTER_RX_DROPPED((byte) 0x4),
     BSN_PORT_COUNTER_RX_ERRORS((byte) 0x5),
     BSN_PORT_COUNTER_TX_BYTES((byte) 0x6),
     BSN_PORT_COUNTER_TX_PACKETS_UNICAST((byte) 0x7),
     BSN_PORT_COUNTER_TX_PACKETS_BROADCAST((byte) 0x8),
     BSN_PORT_COUNTER_TX_PACKETS_MULTICAST((byte) 0x9),
     BSN_PORT_COUNTER_TX_DROPPED((byte) 0xa),
     BSN_PORT_COUNTER_TX_ERRORS((byte) 0xb),
     BSN_PORT_COUNTER_RX_RUNTS((byte) 0xc),
     BSN_PORT_COUNTER_RX_GIANTS((byte) 0xd),
     BSN_PORT_COUNTER_RX_CRC_ERRORS((byte) 0xe),
     BSN_PORT_COUNTER_RX_ALIGNMENT_ERRORS((byte) 0xf),
     BSN_PORT_COUNTER_RX_SYMBOL_ERRORS((byte) 0x10),
     BSN_PORT_COUNTER_RX_PAUSE_INPUT((byte) 0x11),
     BSN_PORT_COUNTER_TX_COLLISIONS((byte) 0x12),
     BSN_PORT_COUNTER_TX_LATE_COLLISIONS((byte) 0x13),
     BSN_PORT_COUNTER_TX_DEFERRED((byte) 0x14),
     BSN_PORT_COUNTER_TX_PAUSE_OUTPUT((byte) 0x15),
     BSN_PORT_COUNTER_RX_PACKETS((byte) 0x16),
     BSN_PORT_COUNTER_TX_PACKETS((byte) 0x17),
     BSN_PORT_COUNTER_RX_LENGTH_ERRORS((byte) 0x18),
     BSN_PORT_COUNTER_RX_OVERFLOW_ERRORS((byte) 0x19),
     BSN_PORT_COUNTER_TX_CARRIER_ERRORS((byte) 0x1a);

     private final byte stableValue;

     private OFBsnPortCounter(byte stableValue) {
        this.stableValue = stableValue;
     }

     public byte getStableValue() {
         return stableValue;
     }
}
